# Generated by Django 4.1.5 on 2023-03-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comapany',
            new_name='Company',
        ),
    ]
